# Generated by Django 6.0.3 on 2026-04-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_historicalsubcategory_subcategory_and_more'),
        ('user', '0003_activitylog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='applicable_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Applicable Tax (%)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='barcode_type',
            field=models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('upc', 'UPC')], default='code128', max_length=20, verbose_name='Barcode Type'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='business_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.branch', verbose_name='Business Location'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='default_purchase_price_exc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Default Purchase Price (Exc. Tax)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='default_purchase_price_inc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Default Purchase Price (Inc. Tax)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='default_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Default Selling Price'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='disable_woocommerce_sync',
            field=models.BooleanField(default=False, verbose_name='Disable WooCommerce Sync'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='enable_imei_or_serial',
            field=models.BooleanField(default=False, verbose_name='Enable Description, IMEI or Serial Number'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='manage_stock',
            field=models.BooleanField(default=False, verbose_name='Manage Stock'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6, verbose_name='Margin (%)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='not_for_selling',
            field=models.BooleanField(default=False, verbose_name='Not For Selling'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_brochure',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Product Brochure'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(choices=[('single', 'Single'), ('variable', 'Variable')], default='single', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='selling_price_tax_type',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20, verbose_name='Selling Price Tax Type'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='service_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Service Staff Time (minutes)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='applicable_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Applicable Tax (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_type',
            field=models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('upc', 'UPC')], default='code128', max_length=20, verbose_name='Barcode Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='business_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_business_location', to='user.branch', verbose_name='Business Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_purchase_price_exc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Default Purchase Price (Exc. Tax)'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_purchase_price_inc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Default Purchase Price (Inc. Tax)'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Default Selling Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='disable_woocommerce_sync',
            field=models.BooleanField(default=False, verbose_name='Disable WooCommerce Sync'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_imei_or_serial',
            field=models.BooleanField(default=False, verbose_name='Enable Description, IMEI or Serial Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='manage_stock',
            field=models.BooleanField(default=False, verbose_name='Manage Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6, verbose_name='Margin (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='not_for_selling',
            field=models.BooleanField(default=False, verbose_name='Not For Selling'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brochure',
            field=models.FileField(blank=True, null=True, upload_to='products/brochures/', verbose_name='Product Brochure'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('single', 'Single'), ('variable', 'Variable')], default='single', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_tax_type',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20, verbose_name='Selling Price Tax Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='service_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Service Staff Time (minutes)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Weight (kg)'),
        ),
    ]
