# Generated by Django 6.0.3 on 2026-04-19 21:43

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_historicalproduct_applicable_tax_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='single_imei_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='Single Product IMEI Numbers'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='single_stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Single Product Quantity'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='applicable_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Applicable Tax (%)'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='imei_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='IMEI Numbers'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6, verbose_name='Margin (%)'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='purchase_price_exc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Purchase Price (Exc. Tax)'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='purchase_price_inc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Purchase Price (Inc. Tax)'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='selling_price_inc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Selling Price (Inc. Tax)'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='selling_price_tax_type',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20, verbose_name='Selling Price Tax Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='single_imei_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='Single Product IMEI Numbers'),
        ),
        migrations.AddField(
            model_name='product',
            name='single_stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Single Product Quantity'),
        ),
        migrations.AddField(
            model_name='variation',
            name='applicable_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Applicable Tax (%)'),
        ),
        migrations.AddField(
            model_name='variation',
            name='imei_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='IMEI Numbers'),
        ),
        migrations.AddField(
            model_name='variation',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6, verbose_name='Margin (%)'),
        ),
        migrations.AddField(
            model_name='variation',
            name='purchase_price_exc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Purchase Price (Exc. Tax)'),
        ),
        migrations.AddField(
            model_name='variation',
            name='purchase_price_inc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Purchase Price (Inc. Tax)'),
        ),
        migrations.AddField(
            model_name='variation',
            name='selling_price_inc_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Selling Price (Inc. Tax)'),
        ),
        migrations.AddField(
            model_name='variation',
            name='selling_price_tax_type',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20, verbose_name='Selling Price Tax Type'),
        ),
        migrations.CreateModel(
            name='HistoricalVariationAttributeValue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('value', models.CharField(max_length=100, verbose_name='Attribute Value')),
                ('value_code', models.CharField(blank=True, max_length=30, verbose_name='Value Code')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attribute', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.variationattribute', verbose_name='Variation Attribute')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Variation Attribute Value',
                'verbose_name_plural': 'historical Variation Attribute Values',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VariationAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('value', models.CharField(max_length=100, verbose_name='Attribute Value')),
                ('value_code', models.CharField(blank=True, max_length=30, verbose_name='Value Code')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.variationattribute', verbose_name='Variation Attribute')),
            ],
            options={
                'verbose_name': 'Variation Attribute Value',
                'verbose_name_plural': 'Variation Attribute Values',
                'ordering': ['attribute__order', 'order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddField(
            model_name='variation',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='variations', to='product.variationattributevalue', verbose_name='Attribute Values'),
        ),
    ]
