# Generated by Django 6.0.3 on 2026-04-19 22:18

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_historicalproduct_single_imei_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='VAT Name')),
                ('rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT Rate (%)')),
                ('tax_type', models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20, verbose_name='Tax Type')),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='low_stock_alert_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Low Stock Alert Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Low Stock Alert Quantity'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(choices=[('single', 'Single'), ('variable', 'Variation'), ('combo', 'Combo')], default='single', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('single', 'Single'), ('variable', 'Variation'), ('combo', 'Combo')], default='single', max_length=20, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='HistoricalVatRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='VAT Name')),
                ('rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT Rate (%)')),
                ('tax_type', models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=20, verbose_name='Tax Type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical VAT Rate',
                'verbose_name_plural': 'historical VAT Rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='vat_rate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.vatrate', verbose_name='VAT Rate'),
        ),
        migrations.AddField(
            model_name='historicalvariation',
            name='vat_rate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.vatrate', verbose_name='VAT Rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.vatrate', verbose_name='VAT Rate'),
        ),
        migrations.AddField(
            model_name='variation',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='product.vatrate', verbose_name='VAT Rate'),
        ),
    ]
