# Generated by Django 6.0.3 on 2026-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_vatrate_historicalproduct_low_stock_alert_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvariation',
            name='variation_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Variation Image'),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variations/', verbose_name='Variation Image'),
        ),
    ]
