# Generated by Django 6.0.3 on 2026-04-21 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_historicalvariation_variation_image_and_more'),
        ('user', '0003_activitylog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_expense_amount_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Expense Amount 1'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_expense_amount_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Expense Amount 2'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_expense_amount_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Expense Amount 3'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_expense_name_1',
            field=models.CharField(blank=True, max_length=120, verbose_name='Additional Expense Name 1'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_expense_name_2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Additional Expense Name 2'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_expense_name_3',
            field=models.CharField(blank=True, max_length=120, verbose_name='Additional Expense Name 3'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='additional_shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Shipping Charges'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Advance Balance'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='attach_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Attach Document'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='business_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.branch', verbose_name='Business Location'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed'), ('percent', 'Percent')], default='none', max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid On'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='pay_term',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pay Term'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='payment_account',
            field=models.CharField(blank=True, max_length=120, verbose_name='Payment Account'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment Amount'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='payment_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment Due'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_banking', 'Mobile Banking'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=30, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='payment_note',
            field=models.TextField(blank=True, verbose_name='Payment Note'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='purchase_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Purchase Tax Amount'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='purchase_tax_rate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.vatrate', verbose_name='Purchase Tax'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference No'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='shipping_details',
            field=models.TextField(blank=True, verbose_name='Shipping Details'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount Percent'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='imei_or_serials',
            field=models.TextField(blank=True, verbose_name='IMEI/Serials'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='line_profit_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Line Profit Margin Percent'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='net_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Cost'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='product_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Product Tax Amount'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='subtotal_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal Before Tax'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='unit_cost_after_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Cost (After Tax)'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='unit_cost_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Cost (Before Tax)'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='unit_cost_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Unit Cost Tax Percent'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseitem',
            name='unit_selling_price_inc_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Selling Price (Inc. Tax)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_expense_amount_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Expense Amount 1'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_expense_amount_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Expense Amount 2'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_expense_amount_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Expense Amount 3'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_expense_name_1',
            field=models.CharField(blank=True, max_length=120, verbose_name='Additional Expense Name 1'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_expense_name_2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Additional Expense Name 2'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_expense_name_3',
            field=models.CharField(blank=True, max_length=120, verbose_name='Additional Expense Name 3'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='additional_shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Additional Shipping Charges'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Advance Balance'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='attach_document',
            field=models.FileField(blank=True, null=True, upload_to='purchases/docs/', verbose_name='Attach Document'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='business_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='user.branch', verbose_name='Business Location'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed'), ('percent', 'Percent')], default='none', max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid On'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pay_term',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pay Term'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_account',
            field=models.CharField(blank=True, max_length=120, verbose_name='Payment Account'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment Amount'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment Due'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_banking', 'Mobile Banking'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=30, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_note',
            field=models.TextField(blank=True, verbose_name='Payment Note'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Purchase Tax Amount'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_taxes', to='product.vatrate', verbose_name='Purchase Tax'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference No'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_details',
            field=models.TextField(blank=True, verbose_name='Shipping Details'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount Percent'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='imei_or_serials',
            field=models.TextField(blank=True, verbose_name='IMEI/Serials'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='line_profit_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Line Profit Margin Percent'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='net_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Cost'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Product Tax Amount'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='subtotal_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal Before Tax'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_cost_after_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Cost (After Tax)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_cost_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Cost (Before Tax)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_cost_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Unit Cost Tax Percent'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_selling_price_inc_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Selling Price (Inc. Tax)'),
        ),
    ]
