

from django.urls import path
from .views import (
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductDetailView,
    UnitListView,
    UnitCreateView,
    UnitUpdateView,
    UnitDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    SubCategoryListView,
    SubCategoryCreateView,
    SubCategoryUpdateView,
    SubCategoryDeleteView,
    VariationAttributeListView,
    VariationAttributeCreateView,
    VariationAttributeUpdateView,
    VariationAttributeDeleteView,
    BrandListView,
    BrandCreateView,
    BrandUpdateView,
    BrandDeleteView,
    WarrantyListView,
    WarrantyCreateView,
    WarrantyUpdateView,
    WarrantyDeleteView,
    VatRateListView,
    VatRateCreateView,
    VatRateUpdateView,
    VatRateDeleteView,
    BranchStockListView,
    BranchStockCreateView,
    BranchStockUpdateView,
    BranchStockDeleteView,
    PurchaseListView,
    PurchaseCreateView,
    PurchaseUpdateView,
    PurchaseDetailView,
    PurchaseDeleteView,
    SupplierDetailView,
    related_object_modal,
    ajax_subcategories_by_category,
    ajax_attribute_values_by_attribute,
    ajax_vat_rate_detail,
    ajax_variations_by_product,
    ajax_unick_by_variation,
    ajax_resolve_unick_from_scanner,
    ajax_search_purchase_products,
)
app_name = "product"
urlpatterns = [
    path("units/", UnitListView.as_view(), name="unit_list"),
    path("units/create/", UnitCreateView.as_view(), name="unit_create"),
    path("units/<int:pk>/edit/", UnitUpdateView.as_view(), name="unit_update"),
    path("units/<int:pk>/delete/", UnitDeleteView.as_view(), name="unit_delete"),

    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("categories/create/", CategoryCreateView.as_view(), name="category_create"),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category_update"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete"),

    path("subcategories/", SubCategoryListView.as_view(), name="subcategory_list"),
    path("subcategories/create/", SubCategoryCreateView.as_view(), name="subcategory_create"),
    path("subcategories/<int:pk>/edit/", SubCategoryUpdateView.as_view(), name="subcategory_update"),
    path("subcategories/<int:pk>/delete/", SubCategoryDeleteView.as_view(), name="subcategory_delete"),

    path("variation-attributes/", VariationAttributeListView.as_view(), name="variation_attribute_list"),
    path("variation-attributes/create/", VariationAttributeCreateView.as_view(), name="variation_attribute_create"),
    path("variation-attributes/<int:pk>/edit/", VariationAttributeUpdateView.as_view(), name="variation_attribute_update"),
    path("variation-attributes/<int:pk>/delete/", VariationAttributeDeleteView.as_view(), name="variation_attribute_delete"),

    path("brands/", BrandListView.as_view(), name="brand_list"),
    path("brands/create/", BrandCreateView.as_view(), name="brand_create"),
    path("brands/<int:pk>/edit/", BrandUpdateView.as_view(), name="brand_update"),
    path("brands/<int:pk>/delete/", BrandDeleteView.as_view(), name="brand_delete"),

    path("warranties/", WarrantyListView.as_view(), name="warranty_list"),
    path("warranties/create/", WarrantyCreateView.as_view(), name="warranty_create"),
    path("warranties/<int:pk>/edit/", WarrantyUpdateView.as_view(), name="warranty_update"),
    path("warranties/<int:pk>/delete/", WarrantyDeleteView.as_view(), name="warranty_delete"),

    path("vat-rates/", VatRateListView.as_view(), name="vat_rate_list"),
    path("vat-rates/create/", VatRateCreateView.as_view(), name="vat_rate_create"),
    path("vat-rates/<int:pk>/edit/", VatRateUpdateView.as_view(), name="vat_rate_update"),
    path("vat-rates/<int:pk>/delete/", VatRateDeleteView.as_view(), name="vat_rate_delete"),

    path("products/", ProductListView.as_view(), name="product_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/view/", ProductDetailView.as_view(), name="product_view"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),

    path("branch-stocks/", BranchStockListView.as_view(), name="branch_stock_list"),
    path("branch-stocks/create/", BranchStockCreateView.as_view(), name="branch_stock_create"),
    path("branch-stocks/<int:pk>/edit/", BranchStockUpdateView.as_view(), name="branch_stock_update"),
    path("branch-stocks/<int:pk>/delete/", BranchStockDeleteView.as_view(), name="branch_stock_delete"),

    path("purchases/", PurchaseListView.as_view(), name="purchase_list"),
    path("purchases/create/", PurchaseCreateView.as_view(), name="purchase_create"),
    path("purchases/<int:pk>/view/", PurchaseDetailView.as_view(), name="purchase_view"),
    path("purchases/<int:pk>/edit/", PurchaseUpdateView.as_view(), name="purchase_update"),
    path("purchases/<int:pk>/delete/", PurchaseDeleteView.as_view(), name="purchase_delete"),
    path("suppliers/<int:pk>/view/", SupplierDetailView.as_view(), name="supplier_view"),

    path("ajax/related/<str:model_name>/create/", related_object_modal, name="related_object_create"),
    path("ajax/related/<str:model_name>/<int:pk>/edit/", related_object_modal, name="related_object_edit"),
    path("ajax/options/subcategories/", ajax_subcategories_by_category, name="ajax_subcategories_by_category"),
    path("ajax/options/attribute-values/", ajax_attribute_values_by_attribute, name="ajax_attribute_values_by_attribute"),
    path("ajax/options/vat-rate/", ajax_vat_rate_detail, name="ajax_vat_rate_detail"),
    path("ajax/options/variations/", ajax_variations_by_product, name="ajax_variations_by_product"),
    path("ajax/options/unick/", ajax_unick_by_variation, name="ajax_unick_by_variation"),
    path("ajax/options/unick/resolve/", ajax_resolve_unick_from_scanner, name="ajax_resolve_unick_from_scanner"),
    path("ajax/options/purchase-products/", ajax_search_purchase_products, name="ajax_search_purchase_products"),
]