# Generated by Django 6.0.3 on 2026-04-08 11:24

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='historicalmultibranch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical MultiBranch', 'verbose_name_plural': 'historical MultiBranches'},
        ),
        migrations.AlterModelOptions(
            name='multibranch',
            options={'ordering': ['title'], 'verbose_name': 'MultiBranch', 'verbose_name_plural': 'MultiBranches'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_staf',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='historicalusers',
            name='customer_group',
        ),
        migrations.AddField(
            model_name='area',
            name='area_staff',
            field=models.ManyToManyField(blank=True, related_name='staffed_areas', to=settings.AUTH_USER_MODEL, verbose_name='Area Staff'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_staff',
            field=models.ManyToManyField(blank=True, related_name='staffed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Branch Staff'),
        ),
        migrations.AddField(
            model_name='historicalroles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='roles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Example: add_user, change_user, delete_user', related_name='custom_roles', to='auth.permission', verbose_name='Direct Permissions'),
        ),
        migrations.AlterField(
            model_name='multibranch',
            name='multi_branch',
            field=models.ManyToManyField(blank=True, to='user.branch'),
        ),
        migrations.AlterField(
            model_name='users',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_area', to='user.area', verbose_name='Area'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='customer_group',
        ),
        migrations.AlterField(
            model_name='users',
            name='mult_branch',
            field=models.ManyToManyField(blank=True, related_name='users_mult_branch', to='user.multibranch', verbose_name='Multi Branch'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/', verbose_name='Profile Picture'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('role_update', 'Role Update')], max_length=20)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Customer Group Name')),
                ('customer_leader', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Leader')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='user.area', verbose_name='Area')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='user.branch', verbose_name='Branch')),
                ('customer_group_staff', models.ManyToManyField(blank=True, related_name='staffed_customer_groups', to=settings.AUTH_USER_MODEL, verbose_name='Customer Group Staff')),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomerGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Customer Group Name')),
                ('customer_leader', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Leader')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.area', verbose_name='Area')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.branch', verbose_name='Branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Customer Group',
                'verbose_name_plural': 'historical Customer Groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('icon', models.CharField(default='fas fa-circle', help_text='e.g. fas fa-users', max_length=50, verbose_name='Font Awesome Icon')),
                ('url', models.CharField(help_text='Example: user_list or /users/', max_length=255, verbose_name='URL or URL Name')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='user.menu', verbose_name='Parent Menu')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Leave empty if every authenticated user with this menu can open it.', related_name='sidebar_menus', to='auth.permission', verbose_name='Required permissions')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalMenu',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('icon', models.CharField(default='fas fa-circle', help_text='e.g. fas fa-users', max_length=50, verbose_name='Font Awesome Icon')),
                ('url', models.CharField(help_text='Example: user_list or /users/', max_length=255, verbose_name='URL or URL Name')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.menu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'historical Menu',
                'verbose_name_plural': 'historical Menus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='roles',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='role_menu_items', to='user.menu', verbose_name='Menu Items'),
        ),
        migrations.AddField(
            model_name='users',
            name='customer_group',
            field=models.ManyToManyField(blank=True, related_name='users_customer_group', to='user.customergroup', verbose_name='Customer Group'),
        ),
    ]
