# Generated by Django 6.0.3 on 2026-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmenu',
            name='url',
            field=models.CharField(help_text='Example: user:user_list or /user/users/', max_length=255, verbose_name='URL or URL Name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(help_text='Example: user:user_list or /user/users/', max_length=255, verbose_name='URL or URL Name'),
        ),
    ]
