# Generated by Django 6.0.3 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_historicalmenu_url_alter_menu_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="changes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
